before_script:
  - sudo apt-get install -y texlive texlive-lang-polish texlive-fonts-extra texlive-latex-extra
script:
  - pdflatex -halt-on-error radio_faq1.tex
before_deploy:
  - git config --local user.name "Tadeusz Magura-Witkowski"
  - git config --local user.email "tadeuszmw+travis@gmail.com"
  - export TRAVIS_TAG=${TRAVIS_TAG:-$(date +'%Y%m%d%H%M%S')-$(git log --format=%h -1)}
  - git tag $TRAVIS_TAG
deploy:
  provider: releases
  api_key: $GITHUB_API_TOKEN
  file: radio_faq1.pdf
  skip_cleanup: true
