name: Build FAQ
on:
  pull_request:
    types:
      - opened
jobs:
  pdf:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v3
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v2
        with:
          root_file: radio_faq1.tex
          extra_system_packages: texlive-full
      - name: Save artifacts
        uses: actions/upload-artifact@v3
        with:
          path: radio_faq1.pdf
